global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - alert_manager:9093
scrape_configs:
 - job_name: node
   static_configs:
    - targets:
       - node_exporter:9100