# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 9a3684d5efe9e62293ddaf2f4344cfba1f612f91c945e2a9cf65d68103bea416
    cni.projectcalico.org/podIP: 192.168.228.123/32
    cni.projectcalico.org/podIPs: 192.168.228.123/32
  creationTimestamp: "2025-05-19T10:40:42Z"
  generateName: nginx-app-69999bf9b8-
  labels:
    app: nginx-app
    pod-template-hash: 69999bf9b8
  name: nginx-app-69999bf9b8-xjrtm
  namespace: demo-app
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: nginx-app-69999bf9b8
    uid: 56f9532d-5924-4281-b65b-12459e826b24
  resourceVersion: "16548"
  uid: 81ce6c92-3d6d-436c-8ce9-d49c44c718bd
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-p4ptp
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-172-31-39-33
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-p4ptp
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-05-19T12:51:49Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-05-19T10:40:42Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-05-19T12:56:57Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-05-19T12:56:57Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-05-19T10:40:42Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://6e4a66394169e2fc17084162a6cdfedff95b683211cb03364bb8c3eafeb73e7e
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:c15da6c91de8d2f436196f3a768483ad32c258ed4e1beb3d367a27ed67253e66
    lastState:
      terminated:
        containerID: containerd://8f8b2763a0e5f68070950874dd001170bf1ccbce90773614307a83044484e4e3
        exitCode: 0
        finishedAt: "2025-05-19T12:51:47Z"
        reason: Completed
        startedAt: "2025-05-19T12:50:20Z"
    name: nginx
    ready: true
    restartCount: 25
    started: true
    state:
      running:
        startedAt: "2025-05-19T12:56:56Z"
  hostIP: 172.31.39.33
  hostIPs:
  - ip: 172.31.39.33
  phase: Running
  podIP: 192.168.228.123
  podIPs:
  - ip: 192.168.228.123
  qosClass: BestEffort
  startTime: "2025-05-19T10:40:42Z"
