server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: nginx_log
  static_configs:
  - targets:
      - nginx_log
    labels:
      job: nginx_log
      __path__: /logs/nginx/*.log
- job_name: apache2_log
  static_configs:
  - targets:
      - apach2_log
    labels:
      job: apache2_log
      __path__: /logs/apache2/*.log