
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    app: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: web-server
        image: pavelstarovoitov/nginx:0.1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
